#!/usr/bin/env bash
# displays /etc/passwd content in the required format

while IFS=: read -r user password uid gid info home shell
do
    echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
