#!/usr/bin/env bash
# This script displays visitor IP and HTTP status code from Apache logs

grep -oE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+.* [0-9]{3} ' apache-access.log | sed -E 's/^([0-9.]+).* ([0-9]{3}) /\1 \2/'
