#!/usr/bin/env bash
# This script groups Apache visitors by IP and HTTP status code and sorts by occurrence

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
